<?xml version="1.0"?>
<!DOCTYPE batchFile [
	<!ELEMENT batchFile (batch+)>
	<!ELEMENT batch (fileSet,settings,destination+)>
	<!ATTLIST batch ID CDATA "" >
	<!ELEMENT fileSet (file+)>
	<!ELEMENT file (#PCDATA)>
	<!ELEMENT settings (windowSize,windowOverlap,samplingRate,normalise,perWindowStats,overallStats,outputType,feature+,aggregator+)>
	<!ELEMENT windowSize (#PCDATA)>
	<!ELEMENT windowOverlap (#PCDATA)>
	<!ELEMENT samplingRate (#PCDATA)>
	<!ELEMENT normalise (#PCDATA)>
	<!ELEMENT perWindowStats (#PCDATA)>
	<!ELEMENT overallStats (#PCDATA)>
	<!ELEMENT outputType (#PCDATA)>
	<!ELEMENT feature (libraryName,active,attribute*)>
	<!ELEMENT libraryName (#PCDATA)>
	<!ELEMENT active (#PCDATA)>
	<!ELEMENT attribute (#PCDATA)>
	<!ELEMENT destination (#PCDATA)>
	<!ELEMENT aggregator (aggregatorName, aggregatorFeature*, aggregatorAttribute*)>
	<!ELEMENT aggregatorName (#PCDATA)>
	<!ELEMENT aggregatorFeature (#PCDATA)>
	<!ELEMENT aggregatorAttribute (#PCDATA)>
]>

<batchFile>
	<batch ID="SampleJAudioBatch">
		<fileSet>
			<file>D:\Swedish House Mafia - Until Now [320]\1-01 Until Now (Continuous DJ Mix) [128].mp3</file>
		</fileSet>
		<settings>
			<windowSize>512</windowSize>
			<windowOverlap>0.0</windowOverlap>
			<samplingRate>16000.0</samplingRate>
			<normalise>false</normalise>
			<perWindowStats>false</perWindowStats>
			<overallStats>true</overallStats>
			<outputType>WEKA</outputType>
			<feature>
				<libraryName>Derivative of Running Mean of Spectral Rolloff Point</libraryName>
				<active>false</active>
				<attribute>0.85</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Strongest Beat</libraryName>
				<active>true</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Spectral Centroid</libraryName>
				<active>true</active>
			</feature>
			<feature>
				<libraryName>Running Mean of Fraction Of Low Energy Windows</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Spectral Rolloff Point</libraryName>
				<active>false</active>
				<attribute>0.85</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Strongest Beat</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Strongest Frequency Via FFT Maximum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Method of Moments</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of LPC</libraryName>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>LPC</libraryName>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Fraction Of Low Energy Windows</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of MFCC</libraryName>
				<active>false</active>
				<attribute>13</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Strongest Frequency Via FFT Maximum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Method of Moments</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Strongest Frequency Via Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Area Method of Moments</libraryName>
				<active>false</active>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Relative Difference Function</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Compactness</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Fraction Of Low Energy Windows</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Spectral Variability</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Compactness</libraryName>
				<active>true</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Method of Moments</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Beat Histogram</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Compactness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of LPC</libraryName>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Beat Sum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Root Mean Square</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>MFCC</libraryName>
				<active>true</active>
				<attribute>4</attribute>
			</feature>
			<feature>
				<libraryName>Zero Crossings</libraryName>
				<active>true</active>
			</feature>
			<feature>
				<libraryName>Fraction Of Low Energy Windows</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Spectral Centroid</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Spectral Flux</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Strength Of Strongest Beat</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Running Mean of Relative Difference Function</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of MFCC</libraryName>
				<active>false</active>
				<attribute>13</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Area Method of Moments</libraryName>
				<active>false</active>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Strongest Frequency Via Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Partial Based Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Fraction Of Low Energy Windows</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Root Mean Square</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>FFT Bin Frequency Labels</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Strongest Frequency Via Zero Crossings</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Strength Of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Relative Difference Function</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Relative Difference Function</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Strength Of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Partial Based Spectral Flux</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Strongest Frequency Via Spectral Centroid</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Area Method of Moments</libraryName>
				<active>false</active>
				<attribute>10</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Spectral Variability</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Strongest Frequency Via FFT Maximum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Strength Of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Beat Sum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Spectral Variability</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Strength Of Strongest Beat</libraryName>
				<active>true</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of LPC</libraryName>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Compactness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of LPC</libraryName>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Zero Crossings</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Strongest Frequency Via Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Partial Based Spectral Centroid</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Running Mean of Compactness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Strongest Frequency Via Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Spectral Rolloff Point</libraryName>
				<active>false</active>
				<attribute>0.85</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Spectral Variability</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Peak Based Spectral Smoothness</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Running Mean of Method of Moments</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Strongest Frequency Via Zero Crossings</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Beat Histogram Bin Labels</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Method of Moments</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Fraction Of Low Energy Windows</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Magnitude Spectrum</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Beat Sum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Area Method of Moments</libraryName>
				<active>false</active>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Peak Based Spectral Smoothness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Relative Difference Function</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Root Mean Square</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Partial Based Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of MFCC</libraryName>
				<active>false</active>
				<attribute>13</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Strength Of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Peak Based Spectral Smoothness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Spectral Flux</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Running Mean of Partial Based Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Peak Based Spectral Smoothness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Spectral Variability</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Beat Sum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Relative Difference Function</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Peak Based Spectral Smoothness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Beat Sum</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Partial Based Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Partial Based Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Root Mean Square</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Partial Based Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Strongest Beat</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Spectral Rolloff Point</libraryName>
				<active>false</active>
				<attribute>0.85</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Area Method of Moments</libraryName>
				<active>false</active>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Strongest Frequency Via FFT Maximum</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Root Mean Square</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Strongest Frequency Via FFT Maximum</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Peak Detection</libraryName>
				<active>false</active>
				<attribute>10</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Spectral Variability</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Peak Based Spectral Smoothness</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Strongest Frequency Via Spectral Centroid</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Partial Based Spectral Centroid</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Strongest Frequency Via FFT Maximum</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of MFCC</libraryName>
				<active>false</active>
				<attribute>13</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Spectral Rolloff Point</libraryName>
				<active>false</active>
				<attribute>0.85</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Method of Moments</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Spectral Rolloff Point</libraryName>
				<active>false</active>
				<attribute>0.85</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of MFCC</libraryName>
				<active>false</active>
				<attribute>13</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of Compactness</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Partial Based Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Running Mean of Strongest Frequency Via Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Root Mean Square</libraryName>
				<active>true</active>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Strongest Frequency Via Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Area Method of Moments</libraryName>
				<active>false</active>
				<attribute>10</attribute>
			</feature>
			<feature>
				<libraryName>Partial Based Spectral Flux</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Running Mean of Strongest Frequency Via Zero Crossings</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Standard Deviation of Strongest Frequency Via Spectral Centroid</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Running Mean of Partial Based Spectral Flux</libraryName>
				<active>false</active>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Standard Deviation of LPC</libraryName>
				<active>false</active>
				<attribute>0.0</attribute>
				<attribute>10</attribute>
				<attribute>100</attribute>
			</feature>
			<feature>
				<libraryName>Derivative of Beat Sum</libraryName>
				<active>false</active>
			</feature>
			<feature>
				<libraryName>Power Spectrum</libraryName>
				<active>false</active>
			</feature>
			<aggregator>
				<aggregatorName>Standard Deviation</aggregatorName>
			</aggregator>
			<aggregator>
				<aggregatorName>Mean</aggregatorName>
			</aggregator>
		</settings>
		<destination>C:\\JADE\\jade\\MusicUs\\jAudioFeatureKey.xml</destination>
		<destination>C:\\JADE\\jade\\MusicUs\\jAudioFeatureValue.xml</destination>
	</batch>
</batchFile>
